### ISSUE TITLE
断点续导报错空指针异常

### ISSUE THREAD

**Issue by 860960342** [hugegraph/hugegraph-loader#111]
在使用hugegraph-loader 0.14.0 导入数据时，由于部分边的节点不存在，出现顶点插入失败，修改后用断点续导模式会报错空指针异常。
![image](https://user-images.githubusercontent.com/58197479/70038335-072f5480-15f3-11ea-975b-100ab8451886.png)
执行命令：
 /homehugegraph-loader-0.10.0/bin/hugegraph-loader -g hugegraph -f /home/test/struct-test.json -s /home/test/test.groovy --incremental-mode true --reload-failure true
导入的顶点和边文件都是JSON格式，报错位置出现在header数组转List，是因为断点续导只适用于CSV数据吗？

**Comment by Linary** [comment]
@860960342 抱歉，这确实是一个BUG，断点续导是适用于JSON文件的，我们会尽快修复此问题。
