### ISSUE TITLE
CUSTOMIZE_STRING方式不能成功导入

### ISSUE THREAD

**Issue by I-DO-NOT-KNOW** [hugegraph/hugegraph-loader#137]
请问下面导入不进去的原因？
struct的配置如下
{
    "vertices":[
        {
            "label":"sysUser",
            "id":"id",
            "update_strategies":{
                "id":"OVERRIDE",
                "name":"OVERRIDE",
                "code":"OVERRIDE",
                "login_name":"OVERRIDE",
                "sex":"OVERRIDE",
                "email":"OVERRIDE"
            },
            "input":{
                "type":"file",
                "path":"loadFile/CSV/sysUserInput.csv",
                "format":"CSV",
                "header":[
                    "id",
                    "name",
                    "code",
                    "login_name",
                    "sex",
                    "email"
                ],
                "charset":"UTF-8",
                "date_format":"yyyy-MM-dd HH:mm:ss"
            },
            "null_values":[
                "NULL",
                "null",
                ""
            ]
        },
        ......
    ],
    "edges":[
        ......
    ]
}

导入结果如下
--------------------------------------------------
total vertex metrics
parse:
    parse success           : 6279                
    parse failure           : 0                   
    parse time              : 0.278s              
    parse rate              : 22586(vertices/s)   
load:
    load success            : 0                   
    load failure            : 6279                
    load time               : 2.055s              
    load rate               : 0(vertices/s)       
--------------------------------------------------
total edge metrics
parse:
    parse success           : 0                   
    parse failure           : 0                   
    parse time              : 0s                  
    parse rate              : -1(edges/s)         
load:
    load success            : 0                   
    load failure            : 0                   
    load time               : 0s                  
    load rate               : -1(edges/s)     

可以解析成功，但是不能导入到数据库中。数据库用的是mysql

**Comment by javeme** [comment]
@I-DO-NOT-KNOW 需要查看下日志里面的错误信息才能分析具体原因，日志见`logs/hugegraph-loader.log`

**Comment by Linary** [comment]
@I-DO-NOT-KNOW 麻烦贴上schema.groovy以及hugegraph-loader.log文件内容，摘一段插入出错的日志信息。

**Comment by I-DO-NOT-KNOW** [comment]
@Linary 排查了好久，后来发现是我的csv格式的数据不正确导致的问题。把数据调整好后，重新初始化了数据库后就好了。
