### ISSUE TITLE
hbase底层存储问题

### ISSUE THREAD

**Issue by LittleWhitec** [hugegraph/hugegraph-loader#142]
使用hbase作为数据存储层，load数据时，发现hbase堆内存占满了，灌完数据后，内存也下不去，分析了dump文件，发现了java.util.concurrent.ConcurrentHashMap$Node[]这个占用是最多的，请问是怎么回事

**Comment by javeme** [comment]
@LittleWhitec hbase堆内存指hbase region-server还是hugegraph-server呢？
如果是hugegraph-server的话，目前默认配置是不会收缩JVM内存的，你可以在启动服务时调整MaxHeapFreeRatio，比如设置70%。

**Comment by LittleWhitec** [comment]
> @LittleWhitec hbase堆内存指hbase region-server还是hugegraph-server呢？
> 如果是hugegraph-server的话，目前默认配置是不会收缩JVM内存的，你可以在启动服务时调整MaxHeapFreeRatio，比如设置70%。

是hbase region-server
