### ISSUE TITLE
当输入源为HDFS 文件时，原始数据中的NULL字段处理

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph-loader#144]
比如在映射文件中已经定义了如下文件（具体信息省略）， 也指定了`null_values`， 然而导入之后，对于在原始表中为`NULL`的字段，在hugegraph 中为`\\N`， 有没有办法设置当字段为text类型时为`''`
    {
      "label": "Manufacturer",
      "input": {
        "type": "hdfs",
        "path": "hdfs://.....",
        "format": "TEXT",
        "delimiter": "|",
        "header": [......],
        "charset": "UTF-8"
      },
      "null_values": ["NULL", "null", ""]
    }

**Comment by Linary** [comment]
@chencjiajy 你是说原始表的NULL，配置了"null_values": ["NULL", "null", ""]之后，进到hugegraph后变成了 \\N 吗？

**Comment by Linary** [comment]
@chencjiajy 配置上"null_values": ["NULL", "null", ""]，并在元数据文件中将包含NULL的属性列添加到nullableKeys 里面，导入时就会忽略NULL值了。形如：
```
schema.vertexLabel("person")
      .properties("name", "age", "city")
      .primaryKeys("name")
      .nullableKeys("age", "city")
      .ifNotExist()
      .create();
```

**Comment by chencjiajy** [comment]
明白了，我确实没有设置nullableKeys
