### ISSUE TITLE
hugegraph编译出错呀，怎么解？

### ISSUE THREAD

**Issue by 597477803** [hugegraph/hugegraph-loader#148]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hugegraph-loader 0.10.2
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.oracle:ojdbc8:jar:12.2.0.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.657 s
[INFO] Finished at: 2020-04-08T18:53:36+08:00
[INFO] Final Memory: 34M/1926M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hugegraph-loader: Could not resolve dependencies for project com.baidu.hugegraph:hugegraph-loader:jar:0.10.2: Failure to find com.oracle:ojdbc8:jar:12.2.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
linyiming@ip-10-64-146-39:~/dev/kg/server/hugegraph-loader$

**Comment by chencjiajy** [comment]
请问你解决了吗

**Comment by Linary** [comment]
@597477803 @chencjiajy 这是oracle的依赖包无法下载导致的。

需要先手动去oracle官网下载`com.oracle:ojdbc8:jar:12.2.0.1`这个jar包，然后在项目目录下执行

```
// $PATH替换为你的路径
mvn install:install-file -Dfile=$PATH/ojdbc8-12.2.0.1.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.2.0.1 -Dpackaging=jar
```

如果不需要以oracle作为数据源导入的话，直接在pom文件中注释oracle的依赖即可：

```
<!--        <dependency>-->
<!--            <groupId>com.oracle</groupId>-->
<!--            <artifactId>ojdbc8</artifactId>-->
<!--            <version>12.2.0.1</version>-->
<!--        </dependency>-->
```
