### ISSUE TITLE
批量加载数值类型主键序列化方式不一致，导致edge关联不上vertex

### ISSUE THREAD

**Issue by LiyuTzyAge** [hugegraph/hugegraph-loader#156]
vertex主键包含int类型property，写入时以int方式序列化。edge写入时主键以字符串方式序列化，导致edge关联不到对应的vertex。

- schema
![image](https://user-images.githubusercontent.com/48547917/83095551-315f5c00-a0d6-11ea-81f6-47b89468d0f8.png)

- data
![image](https://user-images.githubusercontent.com/48547917/83096037-45578d80-a0d7-11ea-9645-61c81c31b33e.png)

- result
![image](https://user-images.githubusercontent.com/48547917/83096055-52747c80-a0d7-11ea-8559-4d38c82ed10e.png)

**Comment by Linary** [comment]
@LiyuTzyAge 感谢反馈。你构造的数据不一致，顶点文件里面marko的年龄是29，边文件里面marko的年龄是10，请先修改一下再试试。

**Comment by LiyuTzyAge** [comment]
还是关联不上
![image](https://user-images.githubusercontent.com/48547917/83115351-cffeb380-a0fc-11ea-9b6f-476d6916146f.png)

**Comment by Linary** [comment]
@LiyuTzyAge 嗯嗯，这个问题已经在这个提交 https://github.com/hugegraph/hugegraph-loader/commit/5579e18c851ad0e9aba1ee3884dba6e36a18fbbe 修复了。

请参考类`src/main/java/com/baidu/hugegraph/loader/builder/ElementBuilder.java`
