### ISSUE TITLE
Failed to start loading, cause: The version of hugegraph-client and hugegraph-server don't match

### ISSUE THREAD

**Issue by sunlin0001** [hugegraph/hugegraph-loader#157]
When running the example provided in hugegraph-loader guided by hugegraph-doc
"sh bin/hugegraph-loader.sh -g hugegraph -f example/file/struct.json -s example/file/schema.groovy"
an error happens:
"Failed to start loading, cause: The version of hugegraph-client and hugegraph-server don't match"

Why is it? 

Thanks

**Comment by javeme** [comment]
@sunlin0001 The versions of of the loader and server are not compatible, which version of hugegraph-server and hugegraph-loader do you use?

**Comment by sunlin0001** [comment]
hugegraph and hugegraph-loader are cloned from GitHub. Following maven operations I get hugegraph-0.11.1 and hugegraph-loader-0.10.2. 

> @sunlin0001 The versions of of the loader and server are not compatible, which version of hugegraph-server and hugegraph-loader do you use?

**Comment by javeme** [comment]
@sunlin0001 There may be incompatibilities between the master branch, please try release-0.11 branch: https://github.com/hugegraph/hugegraph/tree/release-0.11
