### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by pdong524** [hugegraph/hugegraph-loader#158]
在导入数据时出现了如下问题：
ERROR：More than 500 vertices insert error, stop parsing and waiting other insert tasks  finished
请问应该怎么处理呢

顶点和边都是CSV文件
顶点的样式如下：
vertices_id,name_v,price,sex
0,tom0,4355,boy
1,tom1,2911,girl
2,tom2,179,girl
3,tom3,401,girl
         ......
边的样式如下：
edges_id,source_id,target_id,name,value
100000,0,99753,knows0,0.5357575693648292
100001,0,69280,knows1,0.5072589843747404
100002,1,65995,knows2,0.8874184209747202
100003,1,44231,knows3,0.5150836161334686
       ........
编写的schema文件如下：
schema.propertyKey("vertices_id").asInt().ifNotExist().create();
schema.propertyKey("name_v").asText().ifNotExist().create();
schema.propertyKey("price").asInt().ifNotExist().create();
schema.propertyKey("sex").asText().ifNotExist().create();
schema.propertyKey("edges_id").asInt().ifNotExist().create();
schema.propertyKey("source_id").asInt().ifNotExist().create();
schema.propertyKey("target_id").asInt().ifNotExist().create();
schema.propertyKey("name").asText().ifNotExist().create();
schema.propertyKey("value").asDouble().ifNotExist().create();

schema.vertexLabel("person").properties("vertices_id", "name_v", "price","sex").primaryKeys("vertices_id").ifNotExist().create();

schema.edgeLabel("knows").sourceLabel("person").targetLabel("person").properties("edges_id", "source_id","target_id","name","value").ifNotExist().create();

编写的映射文件如下：
{
  "vertices": [
    {
      "label": "person",
      "input": {
        "type": "file",
        "path": "vertices.csv",
        "format": "CSV",
        "charset": "UTF-8"
      }
    }
  ],
  "edges": [
    {
      "label": "knows",
      "source": ["source_id"],
      "target": ["target_id"],
      "input": {
        "type": "file",
        "path": "edges.csv",
        "format": "CSV"
      },
      "mapping": {
        "source_id": "vertices_id",
        "target_id": "vertices_id"
      }
    }
  ]
}

**Comment by pdong524** [comment]
insert-error文件里面是这样说的：
 INSERT ERROR: The primary keys: [name] of vertex label 'person' must be set when using 'PRIMARY_KEY' id strategy
我在schema文件里面指定了主键，请问为什么会出现这种情况呢

**Comment by pdong524** [comment]
顶点的问题解决了：是之前导入过person节点

现在又有了新的问题：
#### INSERT ERROR: Invalid vertex id '1:0'
100000,0,99753,knows0,0.5357575693648292
#### INSERT ERROR: Invalid vertex id '1:31623'
100500,250,31623,knows500,0.32729738572060607
是我的映射文件编写出问题了吗？
vertex id '1:31623'代表什么意思呢

**Comment by javeme** [comment]
@pdong524 导入边时，顶点还没有导入进去，会出现这种错误“INSERT ERROR: Invalid vertex id”，可以在导入时使用`--check-vertex false`关闭检查，或者先把所有顶点导入后再导入边。

**Comment by pdong524** [comment]
感谢！问题已经解决了，是我将边的source_id和target_id错误的写进了schema属性声明中
