### ISSUE TITLE
边导入之后查询不到

### ISSUE THREAD

**Issue by pdong524** [hugegraph/hugegraph-loader#160]
groovy文件中主键的对应部分如下：

schema.vertexLabel("person2").properties("vertices_id", "name_v", "price","sex").primaryKeys("vertices_id").ifNotExist().create();

映射文件中对应部分如下：
"edges": [
    {
      "label": "knows2",
      "source": ["source_id"],
      "target": ["target_id"],
      "input": {
        "type": "file",
        "path": "/opt/graph/initData1/edges.csv",
        "format": "CSV"
      },
      "field_mapping": {
        "source_id": "vertices_id",
        "target_id": "vertices_id"
      }
    }
  ]
请问为什么会找不到边呢？是没有映射到顶点吗

**Comment by javeme** [comment]
@pdong524 如果没有导入顶点的话，请导入顶点之后再进行查询。

**Comment by Linary** [comment]
@pdong524 导入顶点了吗？看下你映射文件的"vertices"块是怎么写的。

**Comment by pdong524** [comment]
感谢！已经成功解决了
