### ISSUE TITLE
Failed to deserialize json

### ISSUE THREAD

**Issue by ezioasche** [hugegraph/hugegraph-loader#168]
json格式保证没错，之前在【hugegraph-0.10.4+loader-0.10.0】load成功的
现在换成master分支最新的【hugegraph-0.11.2+loader-0.10.4】就报错了
后者的新版本都是master分支最新clone下来编译的

ps：当前最新的loader的pom要修改下，ojdbc8的仓库地址已经变了

**Comment by Linary** [comment]
这个是服务端的错还是loader的错，把异常信息一下。
