### ISSUE TITLE
批量导入点/边时，是否可以区分统计哪些是新增，哪些是覆盖导入的？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph-loader#171]
如题，在调用批量接口，导入点/边时，是否可以区分统计哪些是新增，哪些是覆盖导入的？

**Comment by javeme** [comment]
@tmljob 因为底层存储结构是基于lsm-tree的，因此无法统计哪些是覆盖，一定要统计的话必然要牺牲性能。

**Comment by tmljob** [comment]
好的，了解了
