### ISSUE TITLE
是否支持从impala导入数据？

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph-loader#172]
如题，是否考虑支持从impala导入数据？

**Comment by Linary** [comment]
我没用过impala，看impala的介绍，如果你的数据存放在HDFS上应该就能支持的。

**Comment by tmljob** [comment]
loader-0.10.0版本没有支持 Parquet类型文件的读取，拉去了master最新的代码（0.11.0），发现已经支持了Parquet类型文件，但在测试过程中发现如下问题：

-1、 Parquet类型文件读取，只能按照文件读取，无法按照路径读取；
ParquetFileLineFetcher
@Override
	public void openReader(Readable readable) {
		Path path = new Path(this.source().path());
		try {
			HadoopInputFile file = HadoopInputFile.fromPath(path, this.conf);
                        **this.reader = ParquetFileReader.open(file);**
			this.schema = this.reader.getFooter().getFileMetaData().getSchema();
			this.columnIO = new ColumnIOFactory().getColumnIO(this.schema);
		} catch (IOException e) {
			throw new LoadException("Failed to open parquet reader for '%s'", e, readable);
		}
		this.resetOffset();
	}

-2、 Parquet类型文件读取，所有数据在读物时都转为String了，在类型转换时会有问题

ParquetFileLineFetcher

@Override
	public Line fetch() {
		boolean needFetchNext = this.pages == null || this.currRowOffset >= this.pagesRowCount;
		// Read next row group
		if (needFetchNext && !this.fetchNextPage()) {
			return null;
		}

		int fieldSize = this.schema.getFields().size();
		Object[] values = new Object[fieldSize];
		SimpleGroup group = (SimpleGroup) this.recordReader.read();
		for (int fieldIndex = 0; fieldIndex < fieldSize; fieldIndex++) {
			**values[fieldIndex] = group.getValueToString(fieldIndex, 0);**
		}
		String rawLine = StringUtils.join(values, Constants.COMMA_STR);

		this.currRowOffset++;
		this.increaseOffset();
		/*
		 * NOTE: parquet file actually corresponds to a table structure, doesn't need to
		 * skip line or match header
		 */
		return new Line(rawLine, this.source().header(), values);
	}

impala 里面的timestamp类型，是INT96的，在转为Date时，直接按照如下字符串转换报错：
Unparseable date: "Int96Value{Binary{12 constant bytes, [-64, -29, 122, 21, 66, 57, 0, 0, 17, -123, 37, 0]}}", expect format: yyyy-MM-dd HH:mm:ss

- 3、读取HDFS数据源，不支持Kerberos验证。

如上几个问题，1&2非常影响使用，在大数据量的情况下，不可能按照1个个Parquet逐个映射导入，请看下可否修复。
@Linary

**Comment by Linary** [comment]
@tmljob 感谢贡献，我们尽快review。
