### ISSUE TITLE
file_filter中的extensions要如何使用？

### ISSUE THREAD

**Issue by junzhewenming** [hugegraph/hugegraph-loader#196]
在struct.json文件中写成了
`"input": {
    "type":"hdfs",
    "path": "...",
    "file_filter": {
        "extensions": "*"
    }
}`
报IllegalArgumentException: Cannot deserialize instance of `java.util.HashSet<java.lang.Object>` out of VALUE_STRING token

**Comment by Linary** [comment]
@junzhewenming 得加个方括号，可以写多个。
```
"file_filter": {
  "extensions": ["txt", "csv"]
}
```
