### ISSUE TITLE
Timed task

### ISSUE THREAD

**Issue by GitHubMaWu** [hugegraph/hugegraph-loader#202]
是否支持定时更新

**Comment by imbajin** [comment]
啥意思, 是说定时导入/更新一批数据么?

如果是上面的需求, 似乎自己用 `crontab` 类脚本定时执行 loader 更合适呢, 你还能方便的自定义

**Comment by GitHubMaWu** [comment]
是这个意思，看到了上面的issue不支持kafka这种流处理，可以通过linux的cron来定时执行批处理。谢谢
