### ISSUE TITLE
[Question] 关于数据源映射文件的一些疑问

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph-loader#220]
### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Loader-Issues](https://github.com/hugegraph/hugegraph-loader/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: latest
- Loader Version: v0.11.1

### Your Question (问题描述)

1.关于文档中描述，下图
![image](https://user-images.githubusercontent.com/43004817/125407483-82223900-e3ec-11eb-8eb7-c3fb591938ac.png)
如果我name和id属性值一样，是否可以不采取替换方式？导入数据时，默认总是按源顶点和目标顶点的 id进行拼接去找name吗？如果编写边映射规则时，指定field_mapping，类似 "field_mapping": {"source_name": "name", "target_name": "name"},它还用拼接id去找name吗？是否直接就能按name找？

2.在编写顶点或者边映射规则时，如何规定对数据进行类型转换，比如我创建属性时规定id为int，但是csv文件中都是字符串，这种我需要显式的进行这种类型转换吗还是loader会帮我做？

3.在编写边映射规则时，只有对于源顶点和目标顶点的字段映射，那要是csv文件里还有边属性的值，应该怎么编写映射规则对边属性进行赋值？

4.如果id策略为useCustomizeNumberId()，导入数据时，structs里的vertices里的id需要指定列作为id，写法是
"vertices": [
        {
          "label": "U",
          "id": "id",
        }
      ]
还是：
"vertices": [
        {
          "label": "U",
          "id": ["id"]
        }
      ]

### Vertex/Edge example (问题点 / 边数据举例)

```javascript
边数据类似：
source_name,target_name,FDT
332318347,223639953,1577588865

边创建语句类似：
schema.edgeLabel("FD").sourceLabel("U").targetLabel("U").properties("FDT").ifNotExist().create();
```

### Schema [VertexLabel, EdgeLabel, IndexLabel] (元数据结构)

```javascript
顶点创建语句：
schema.vertexLabel("U").useCustomizeNumberId().properties("id","name") .ifNotExist().create();

struct.json类似：
{
  "version": "2.0",
  "structs": [
    {
      "id": "1",
      "skip": false,
      "input": {
        "type": "FILE",
        "path": "n_user.csv",
        "file_filter": {
          "extensions": [
            "*"
          ]
        },
        "format": "CSV",
        "delimiter": ",",
        "date_format": "timestamp",
        "time_zone": "GMT+8",
        "skipped_line": {
          "regex": "(^#|^//).*|"
        },
        "compression": "NONE",
		"header": null,
        "charset": "UTF-8",
        "list_format": null
      },
      "vertices": [
        {
          "label": "U",
          "skip": false,
          "id": "id",
          "unfold": false,
          "field_mapping": {},
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],
          "update_strategies": {}
        }
      ],
      "edges": []
    },
    {
      "id": "2",
      "skip": false,
      "input": {
        "type": "FILE",
        "path": "n_page.csv",
        "file_filter": {
          "extensions": [
            "*"
          ]
        },
        "format": "CSV",
        "delimiter": ",",
        "date_format": "timestamp",
        "time_zone": "GMT+8",
        "skipped_line": {
          "regex": "(^#|^//).*|"
        },
        "compression": "NONE",
        "header": null,
        "charset": "UTF-8",
        "list_format": null
      },
      "vertices": [
        {
          "label": "P",
          "skip": false,
          "id": "id",
          "unfold": false,
          "field_mapping": {},
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],
          "update_strategies": {}
        }
      ],
      "edges": []
    },
    {
      "id": "3",
      "skip": false,
      "input": {
        "type": "FILE",
        "path": "edge_fu.csv",
        "file_filter": {
          "extensions": [
            "*"
          ]
        },
        "format": "CSV",
        "delimiter": null,
        "date_format": "timestamp",
        "time_zone": "GMT+8",
        "skipped_line": {
          "regex": "(^#|^//).*|"
        },
        "compression": "NONE",
        "header": null,
        "charset": "UTF-8",
        "list_format": null
      },
      "vertices": [],
      "edges": [
        {
          "label": "FP",
          "skip": false,
          "source": [
            "source_name"
          ],
          "unfold_source": false,
          "target": [
            "target_name"
          ],
          "unfold_target": false,
          "field_mapping": {
            "source_name": "name",
            "target_name": "name"
          },
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],
          "update_strategies": {}
        }
      ]
    }
}
```

**Comment by imbajin** [comment]
不好意思问题有点多, 之后有空来看看, 关于导入相关配置的, 你可以先简化一下模型自测一下是否可行

**Comment by wanglunwei** [comment]
边的数据是CSV格式的 有个配置的例子不？官方文档中没有边是CSV配置例子？

**Comment by imbajin** [comment]
> 边的数据是CSV格式的 有个配置的例子不？官方文档中没有边是CSV数据格式的边映射的例子。

从解析文本看 CSV 本质和 text 没有啥区别呢, 只是一种特殊的 text 罢了

**Comment by wanglunwei** [comment]
帮忙看看下面的配置文件配置的对不？导数据一直报错：Failed to load, cause: java.io.InterruptedIOException
{
  "version": "2.0",
  "structs": [
    {
      "id": "1",
      "skip": false,
      "input": {
        "type": "FILE",
        "path": "/home/ocdp/example2/dw_product_vertex_ds_new2/dw_product_vertex_ds_new.csv",
        "file_filter": {
          "extensions": [
            "*"
          ]
        },
        "format": "CSV",
        "delimiter": ",",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "time_zone": "GMT+8",
        "skipped_line": {
          "regex": "(^#|^//).*|"
        },
        "compression": "NONE",
        "header": [
          "m",
          "vertex_type",
          "vertex_is_n",
	  "id_card",
	  "vertex_id",
          "month",
          "day"
        ],
        "charset": "UTF-8",
        "list_format": null
      },
      "vertices": [
        {
          "label": "phone",
          "skip": false,
          "id": null,
          "unfold": false,
          "field_mapping": {},
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],
          "update_strategies": {}
        }
      ],
      "edges": []
    },
    {
      "id": "2",
      "skip": false,
      "input": {
        "type": "FILE",
        "path": "/home/ocdp/example2/dw_product_vertex_iden_ds_new2/dw_product_vertex_iden_ds_new.csv",
        "file_filter": {
          "extensions": [
            "*"
          ]
        },
        "format": "CSV",
        "delimiter": ",",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "time_zone": "GMT+8",
        "skipped_line": {
          "regex": "(^#|^//).*|"
        },
        "compression": "NONE",
        "header": [
	  "m",
          "vertex_type",
          "vertex_is_n",
	  "id_card",
	  "vertex_id",
	  "day",
	  "month"
		  ],
        "charset": "UTF-8",
        "list_format": null
      },
      "vertices": [
        {
          "label": "iden_cards",
          "skip": false,
          "id": null,
          "unfold": false,
          "field_mapping": {},
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],
          "update_strategies": {}
        }
      ],
      "edges": []
    },
    {
      "id": "4",
      "skip": false,
      "input": {
        "type": "FILE",
        "path": "/home/ocdp/example2/own_phone_ds2/own_phone_ds",
        "file_filter": {
          "extensions": [
            "*"
          ]
        },
        "format": "CSV",
        "delimiter": ",",
        "date_format": "yyyy-MM-dd HH:mm:ss",
        "time_zone": "GMT+8",
        "skipped_line": {
          "regex": "(^#|^//).*|"
        },
        "compression": "NONE",
        "header": [
          "source_name",
          "target_name",
          "phone_relation_ds_desc"
        ],
        "charset": "UTF-8",
        "list_format": null
      },
      "vertices": [],
      "edges": [
        {
          "label": "own_phone_ds",
          "skip": false,
          "source": [
            "source_name"
          ],
          "unfold_source": false,
          "target": [
            "target_name"
          ],
          "unfold_target": false,
          "field_mapping": {
            "source_name": "m",
            "target_name": "m"
          },
          "value_mapping": {},
          "selected": [],
          "ignored": [],
          "null_values": [
            ""
          ],
          "update_strategies": {}
        }
      ]
    }
  ]
}

**Comment by imbajin** [comment]
@wanglunwei 麻烦单独开一个 issue, 把 schema 文件贴到对应合适的代码块处, 有个排版和高亮.

另外可以把上下文说清楚一点, 包括报错的详细堆栈截图之类的

**Comment by wanglunwei** [comment]
找到问题的原因了，selected需要配置所需要的字段才行，  请教无向边怎么设置？

**Comment by imbajin** [comment]
> 找到问题的原因了，selected需要配置所需要的字段才行， 请教无向边怎么设置？

目前没支持直接设置无向边, 两个方向各导入一次则为双向边/无向边. 支持也只是一个语法糖(帮把某个类型的 lable 全部创建两条)
