### ISSUE TITLE
[Bug] 字符串转长整数报错

### ISSUE THREAD

**Issue by s348268281** [hugegraph/hugegraph-loader#221]
### Before submit

- [X] 我已经确认现有的 [Server-Issues](https://github.com/hugegraph/hugegraph/issues) 与 [Loader-Issues](https://github.com/hugegraph/hugegraph-loader/issues) 中没有相同 / 重复问题

### Environment (环境信息)

- Server Version: latset
- Loader Version: v0.11.1

### Expected & Actual behavior (期望与实际表现)

属性创建语句
schema.propertyKey("PN").asLong().ifNotExist().create();

报错记录：
#### PARSE ERROR: Failed to convert value(key=PN) '18210570331'(class java.lang.String) to Number

'18210570331'是csv文件中的字符串（电话号码），转长整型时报错

**Comment by imbajin** [comment]
麻烦给一下确切的 csv 行原始数据

然后你可以试试是否可以复现? 看提示识别为了字符串, 为何呢? csv 的话应该直接识别为数字才对

**Comment by s348268281** [comment]
> 麻烦给一下确切的 csv 行原始数据
> 
> 然后你可以试试是否可以复现? 看提示识别为了字符串, 为何呢? csv 的话应该直接识别为数字才对, 还需要一些上下文信息

抱歉，重启容器后可以了，忘删帖子了
