### ISSUE TITLE
hdfs-jdbs 效率与 分支合并

### ISSUE THREAD

**Issue by platypus0127** [hugegraph/hugegraph-loader#30]
有个问题请教一下，我编译了最新的hdfs-jdbc 0.7.1版本，发现load的数据不够快，同时也不支持最新的0.8server，我是不是可以把hdfs-jdbc和master分支合并呀？
@zhoney @Linary

**Comment by Linary** [comment]
@platypus0127 抱歉，该分支的代码还在评审阶段，暂时还不能使用的。

**Comment by platypus0127** [comment]
好的
