### ISSUE TITLE
More than 500 vertices insert

### ISSUE THREAD

**Issue by denghaiai** [hugegraph/hugegraph-loader#34]
When i use the hugegraph-loader  insert more than 500 vertices ，console print the Error： More than 500 vertices insert.

**Comment by suesunss** [comment]
This is basically because of the fact that, by default, if more than 500 records are wronly inserted, the loading process will stop. 

please refer to the parameter

```
--max-insert-errors
```
in the [official doc](https://hugegraph.github.io/hugegraph-doc/quickstart/hugegraph-loader.html)

**Comment by suesunss** [comment]
Also, please refer to the same issue [here](https://github.com/hugegraph/hugegraph-loader/issues/19)
