### ISSUE TITLE
导入结点关系问题

### ISSUE THREAD

**Issue by nohunt** [hugegraph/hugegraph-loader#36]
date,calling,called
"2018-08-01","1000","10086"
"2018-08-11","1000","10086"
"2018-08-15","1000","10086"
"2018-08-07","1000","10086"

上面的数据，怎么通过HugeGraph-Loader，把date,当成关系属性，属性类型为list.且“1000”与“10086”只有一条连线关系。导入到hugegraph

针对上面还有几点疑问：
1)对于属性类型是list的，是不是不能建立索引
2）能否对属性类型是list的指定的值进行过滤查询

**Comment by Linary** [comment]
> 上面的数据，怎么通过HugeGraph-Loader，把date,当成关系属性，属性类型为list.且“1000”与“10086”只有一条连线关系。导入到hugegraph

先说结论：hugegraph目前是做不到你的这个要求的。
具体原因是loader是按行处理数据源的，每一行数据都会被转化为一条插入语句（单条或属于批量），并且每一行的源顶点、目标顶点以及属性key都一样，所以后面的行会覆盖前面的行。

> 针对上面还有几点疑问：
1)对于属性类型是list的，是不是不能建立索引
2）能否对属性类型是list的指定的值进行过滤查询

值为list的属性的确不能创建索引，自然也没法进行过滤查询。

其实这里更好的方案是令date作为sortkey，不过这样会有多条边（有悖于你的要求：只有一条连线关系）。这样的好处有两个：
1. 可以建立索引，自然可以对date属性做过滤查询
2. 即使不建立索引，也可以以“1000”或“10086”为基准点做过滤查询

**Comment by nohunt** [comment]
> > 上面的数据，怎么通过HugeGraph-Loader，把date,当成关系属性，属性类型为list.且“1000”与“10086”只有一条连线关系。导入到hugegraph
> 
> 先说结论：hugegraph目前是做不到你的这个要求的。
> 具体原因是loader是按行处理数据源的，每一行数据都会被转化为一条插入语句（单条或属于批量），并且每一行的源顶点、目标顶点以及属性key都一样，所以后面的行会覆盖前面的行。
> 
> > 针对上面还有几点疑问：
> > 1)对于属性类型是list的，是不是不能建立索引
> > 2）能否对属性类型是list的指定的值进行过滤查询
> 
> 值为list的属性的确不能创建索引，自然也没法进行过滤查询。
> 
> 其实这里更好的方案是令date作为sortkey，不过这样会有多条边（有悖于你的要求：只有一条连线关系）。这样的好处有两个：
> 
> 1. 可以建立索引，自然可以对date属性做过滤查询
> 2. 即使不建立索引，也可以以“1000”或“10086”为基准点做过滤查询

谢谢答复，如果令date作为sortkey的方案的话，虽然可以解决时间属性查询 的问题，但当date有多个不同值的，是不是在关系展示时，会显的很凌乱呢？

**Comment by Linary** [comment]
如果想看到所有的date，展示出来确实会有些凌乱，不过用表格视图查看就还好。

**Comment by zhoney** [comment]
@nohunt 

> date,calling,called
"2018-08-01","1000","10086"
"2018-08-11","1000","10086"
"2018-08-15","1000","10086"
"2018-08-07","1000","10086"

此类数据比较常见的两种存储方案：

### 方案1：multiTimes+sortKey(date)，每条边存储一条记录，

优点：
1. 可以建立索引，进行过滤查询
2. 支持sortKeys的过滤查询
3. 可以使用hugegraph-loader导入

缺点：
1. 每条记录一条边，数据膨胀（相对于方案2）

### 方案2：singleTime+list properties

优点：
1. 边的数目少（相对于方案1）
2. 关系（展示）比较清晰

缺点：
1. list property无法建立索引，进行高效过滤

> 仍然可根据属性过滤。查询时整个list property作为整体取出，可以通过gremlin语句进行过滤，比如: g.V('10086').outE().where(values('date').is(between("2018-08-05", "2018-08-10")))

2. hugegraph-loader目前无法支持数据导入，需要自行使用hugegraph-client进行导入或者改造hugegraph-loader

**Comment by suesunss** [comment]
补充一个基于 list 的过滤方法：

```java
g.V().where(values('property_name').unfold().is(search_value))
```

[参考 StackOverflow](https://stackoverflow.com/questions/51920699/gremlin-how-do-i-find-vertices-whose-properties-contain-a-certain-values)
