### ISSUE TITLE
load导入不认识-h参数

### ISSUE THREAD

**Issue by sunlc210** [hugegraph/hugegraph-loader#37]
load导入数据，没有地方设置hugegraph server服务器地址，加入 -h 报错不认识。
我看git book里面是可以的，我用的是0.7版本

**Comment by sunlc210** [comment]
这是我的命令
 bin/hugegraph-loader -g hugegraph -f ./struct.json -s ./schema.groovy -h app120 --check-vertex false 
报错
Exception in thread "main" com.beust.jcommander.ParameterException: Invalid value of argument '-h': 'app120'

**Comment by zhoney** [comment]
@sunlc210 感谢反馈！

可以使用 `-h ip`的方式解决这个问题。

`-h`的参数value，是通过regex匹配进行检查的，目前合法值是`http://xxx.yyy.zzz`或者`http://ip`两种方式，后续我们会改进这个regex匹配。
