### ISSUE TITLE
PROPERTY_KEY with name 'xxx﻿' does not exist

### ISSUE THREAD

**Issue by yuyongqiang1** [hugegraph/hugegraph-loader#56]
when i run `bin/hugegraph-loader -g hugegraph -f example/struct.json -s example/schema.groovy`  i get this error: `Vertices has been imported: Exception in thread "main" class com.baidu.hugegraph.exception.NotFoundException: PROPERTY_KEY with name '﻿actorID' does not exist`

`schema.groovy` as follow:
schema.propertyKey("actorID").asText().ifNotExist().create();
schema.propertyKey("moveID").asText().ifNotExist().create();
schema.vertexLabel("Actor").properties("actorID").primaryKeys("actorID").ifNotExist().create();
schema.vertexLabel("Move").properties("moveID").primaryKeys("moveID").ifNotExist().create();
schema.edgeLabel("ACTED_IN").sourceLabel("Actor").targetLabel("Move").ifNotExist().create();

in above code, i indicate that if it doesn't exist,i create it. So this error really confuse me
`struct.json` as follow:
{
  "vertices": [
    {
      "label": "Actor",
      "input": {
        "type": "file",
        "path": "example/actor.csv",
        "format": "CSV"
      }
    },
    {
      "label": "Move",
      "input": {
        "type": "file",
        "path": "example/move.csv",
        "format": "CSV"
      }
    }
  ],
  "edges": [
    {
      "label": "ACTED_IN",
      "source": ["actorID"],
      "target": ["moveID"],
      "input": {
        "type": "file",
        "path": "example/edge.csv",
        "format": "CSV"
      },
        "mapping": {
        "actorID": "actorID",
        "moveID": "moveID"
      }
    }
  ]
}

`actor.csv` as follow:
actorID
1
2
3
4
`movie.csv` as follow:
moveID
1
2
3
4
`edge.csv` as follow:
actorID,moveID
1,1
2,2
3,3
4,4

thinks for help

**Comment by Linary** [comment]
1. You can check if the property keys is created successfully via `curl http://localhost:8080/graphs/hugegraph/schema/propertykeys`
2. You should check file name, column name matching each other. I find it `"path": "example/move.csv",` is not matched with file name `movie.csv`

**Comment by yuyongqiang1** [comment]
Thank you for your reply,I am too careless.
According to your suggestion, I find that property keys is not set successfully,The specific results returned by the command are as follows:
{"propertykeys": [{"id":10,"name":"movieID","data_type":"TEXT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":7,"name":"weight","data_type":"DOUBLE","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":6,"name":"price","data_type":"INT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":9,"name":"moveID","data_type":"INT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":8,"name":"actorID","data_type":"INT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":3,"name":"city","data_type":"TEXT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":2,"name":"age","data_type":"INT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":5,"name":"date","data_type":"TEXT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":4,"name":"lang","data_type":"TEXT","cardinality":"SINGLE","properties":[],"user_data":{}},{"id":1,"name":"name","data_type":"TEXT","cardinality":"SINGLE","properties":[],"user_data":{}}]}
Can you give me some advice on how to set property keys correctly?

**Comment by Linary** [comment]
Have you loaded other data before, if not, it is recommended that you delete the previous data directly and then re-load.

**Comment by Linary** [comment]
You can delete data and schema via client API
```
// Clear edge
graph().listEdges().forEach(e -> graph().removeEdge(e.id()));
// Clear vertex
graph().listVertices().forEach(v -> graph().removeVertex(v.id()));

List<Long> ilTaskIds = new ArrayList<>();
// Clear schema
schema().getIndexLabels().forEach(il -> {
    ilTaskIds.add(schema().removeIndexLabelAsync(il.name()));
});
ilTaskIds.forEach(taskId -> waitUntilTaskCompleted(taskId));

List<Long> elTaskIds = new ArrayList<>();
schema().getEdgeLabels().forEach(el -> {
    elTaskIds.add(schema().removeEdgeLabelAsync(el.name()));
});
elTaskIds.forEach(taskId -> waitUntilTaskCompleted(taskId));

List<Long> vlTaskIds = new ArrayList<>();
schema().getVertexLabels().forEach(vl -> {
    vlTaskIds.add(schema().removeVertexLabelAsync(vl.name()));
});
vlTaskIds.forEach(taskId -> waitUntilTaskCompleted(taskId));

schema().getPropertyKeys().forEach(pk -> {
    schema().removePropertyKey(pk.name());
});
```

**Comment by yuyongqiang1** [comment]
thank you Sincerely
